version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - .data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myfuckingshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=15042021
  web:
    build: .
    command: python manage.py runserver  0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=myfuckingshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=15042021
    depends_on:
      - db